# Generated by Django 6.1 on 2026-09-07 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvioOperativo',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('percorso', models.CharField(max_length=250)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
