# Generated by Django 6.1 on 2026-09-05 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produzione', '0002_tipolavorazione_cicloproduzione_lavorazione_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroControllo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo_dato', models.CharField(choices=[('DECIMALE', 'Decimale'), ('INTERO', 'Intero'), ('BOOLEANO', 'Booleano'), ('TESTO', 'Testo')], max_length=10)),
                ('unita_misura', models.CharField(blank=True, max_length=30)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlloRichiestoTipoLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obbligatorio', models.BooleanField(default=True)),
                ('valore_minimo', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('valore_massimo', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('valore_booleano_atteso', models.BooleanField(blank=True, null=True)),
                ('determina_conformita', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('tipo_lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlli_richiesti', to='produzione.tipolavorazione')),
                ('parametro_controllo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiti', to='qualita.parametrocontrollo')),
            ],
            options={
                'ordering': ['ordine', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ControlloQualita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_decimale', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('valore_intero', models.BigIntegerField(blank=True, null=True)),
                ('valore_booleano', models.BooleanField(blank=True, null=True)),
                ('valore_testo', models.TextField(blank=True)),
                ('conforme', models.BooleanField()),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('note', models.TextField(blank=True)),
                ('eseguito_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlli_qualita', to='produzione.lavorazione')),
                ('controllo_richiesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misurazioni', to='qualita.controllorichiestotipolavorazione')),
            ],
            options={
                'ordering': ['data_ora', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='controllorichiestotipolavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('valore_minimo__isnull', True), ('valore_massimo__isnull', True), ('valore_minimo__lte', models.F('valore_massimo')), _connector='OR'), name='quality_limits_order'),
        ),
    ]
