# Generated by Django 6.1 on 2026-09-07 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_lotto_lavorazione_origine_and_more'),
        ('produzione', '0003_risorsaproduttiva_unitalavorazione_and_more'),
        ('qualita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('data_ora_apertura', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('FORNITORE', 'Fornitore'), ('CLIENTE', 'Cliente'), ('ALTRO', 'Altro')], default='INTERNA', max_length=10)),
                ('descrizione', models.TextField()),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('IN_GESTIONE', 'In gestione'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('aperta_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nc_aperte', to=settings.AUTH_USER_MODEL)),
                ('controllo_qualita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='qualita.controlloqualita')),
                ('lavorazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='produzione.lavorazione')),
                ('lotto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='magazzino.lotto')),
                ('risorsa_produttiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='produzione.risorsaproduttiva')),
            ],
            options={
                'verbose_name_plural': 'Non conformità',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='AzioneNonConformita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tipo_azione', models.CharField(choices=[('QUARANTENA', 'Quarantena'), ('REINTEGRO', 'Reintegro'), ('SCARTO', 'Scarto'), ('RILAVORAZIONE', 'Rilavorazione'), ('CORREZIONE_PROCESSO', 'Correzione processo'), ('ALTRO', 'Altro')], max_length=20)),
                ('descrizione', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('eseguita_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='azioni_nc_eseguite', to=settings.AUTH_USER_MODEL)),
                ('lavorazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='azioni_nc', to='produzione.lavorazione')),
                ('movimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='azioni_nc', to='magazzino.movimento')),
                ('non_conformita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azioni', to='qualita.nonconformita')),
            ],
            options={
                'ordering': ['data_ora', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='VerificaNonConformita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('esito', models.CharField(choices=[('EFFICACE', 'Efficace'), ('NON_EFFICACE', 'Non efficace')], max_length=12)),
                ('descrizione', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('controllo_qualita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifiche_nc', to='qualita.controlloqualita')),
                ('non_conformita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifiche', to='qualita.nonconformita')),
                ('verificata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifiche_nc_eseguite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_ora', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='nonconformita',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='nc_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='nonconformita',
            constraint=models.CheckConstraint(condition=models.Q(('stato__in', ['APERTA', 'IN_GESTIONE', 'CHIUSA'])), name='nc_stato_valido'),
        ),
        migrations.AddConstraint(
            model_name='azionenonconformita',
            constraint=models.UniqueConstraint(fields=('movimento',), name='nc_azione_movimento_unico'),
        ),
        migrations.AddConstraint(
            model_name='azionenonconformita',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movimento__isnull', False), ('tipo_azione__in', ['QUARANTENA', 'REINTEGRO', 'SCARTO'])), models.Q(('movimento__isnull', True), ('tipo_azione__in', ['RILAVORAZIONE', 'CORREZIONE_PROCESSO', 'ALTRO'])), _connector='OR'), name='nc_azione_movimento_coerente'),
        ),
        migrations.AddConstraint(
            model_name='azionenonconformita',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_azione', 'RILAVORAZIONE'), _negated=True), ('lavorazione__isnull', False), _connector='OR'), name='nc_rilavorazione_riferita'),
        ),
        migrations.AddConstraint(
            model_name='verificanonconformita',
            constraint=models.CheckConstraint(condition=models.Q(('esito__in', ['EFFICACE', 'NON_EFFICACE'])), name='nc_verifica_esito_valido'),
        ),
    ]
