# Generated by Django 6.1 on 2026-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualita', '0002_nonconformita_azionenonconformita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlloqualita',
            name='esito',
            field=models.CharField(blank=True, choices=[('C', 'Conforme'), ('NC', 'Non conforme'), ('NA', 'Non applicabile')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='controllorichiestotipolavorazione',
            name='funzione',
            field=models.CharField(blank=True, choices=[('', 'Generico'), ('BRIX', 'Brix tank'), ('PH', 'pH tank'), ('BATCH', 'Tracciato batch'), ('PAST', 'Seconda pastorizzazione'), ('VUOTO', 'Shock termico e vuoto')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='controllorichiestotipolavorazione',
            name='massimo_esclusivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controllorichiestotipolavorazione',
            name='minimo_esclusivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parametrocontrollo',
            name='tipo_dato',
            field=models.CharField(choices=[('DECIMALE', 'Decimale'), ('INTERO', 'Intero'), ('BOOLEANO', 'Booleano'), ('TESTO', 'Testo'), ('ESITO', 'Esito C / NC / NA')], max_length=10),
        ),
    ]
