# Generated by Django 6.1 on 2026-09-05 10:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=40, unique=True)),
                ('ragione_sociale', models.CharField(max_length=250)),
                ('partita_iva', models.CharField(blank=True, max_length=30)),
                ('codice_fiscale', models.CharField(blank=True, max_length=30)),
                ('indirizzo', models.CharField(blank=True, max_length=250)),
                ('cap', models.CharField(blank=True, max_length=20)),
                ('comune', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('nazione', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Fornitori',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='Ubicazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Ubicazioni',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='figli', to='anagrafiche.categoriaarticolo')),
            ],
            options={
                'verbose_name_plural': 'Categorie articolo',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=60, unique=True)),
                ('descrizione', models.CharField(max_length=250)),
                ('unita_misura', models.CharField(choices=[('KG', 'Chilogrammi'), ('L', 'Litri'), ('PZ', 'Pezzi')], max_length=2)),
                ('criterio_rotazione', models.CharField(choices=[('FIFO', 'FIFO'), ('FEFO', 'FEFO'), ('NESSUNO', 'Nessuno')], default='FEFO', max_length=7)),
                ('tracciabilita_lotto', models.BooleanField(default=True)),
                ('scorta_minima', models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articoli', to='anagrafiche.categoriaarticolo')),
            ],
            options={
                'verbose_name_plural': 'Articoli',
                'ordering': ['codice'],
            },
        ),
        migrations.AddConstraint(
            model_name='articolo',
            constraint=models.CheckConstraint(condition=models.Q(('scorta_minima__gte', 0)), name='articolo_scorta_non_negativa'),
        ),
        migrations.AddConstraint(
            model_name='articolo',
            constraint=models.CheckConstraint(condition=models.Q(('unita_misura__in', ['KG', 'L', 'PZ'])), name='articolo_unita_valida'),
        ),
        migrations.AddConstraint(
            model_name='articolo',
            constraint=models.CheckConstraint(condition=models.Q(('criterio_rotazione__in', ['FIFO', 'FEFO', 'NESSUNO'])), name='articolo_rotazione_valida'),
        ),
    ]
