# Generated by Django 6.1 on 2026-09-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0002_unita_misura_lt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='unita_misura',
            field=models.CharField(choices=[('KG', 'KG'), ('LT', 'LT'), ('PZ', 'PZ')], max_length=2),
        ),
    ]
