# Generated by Django 6.1 on 2026-09-05 10:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_lotto', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ACQUISTO', 'Acquisto'), ('PRODUZIONE', 'Produzione')], max_length=10)),
                ('data_produzione', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('codice_univoco_produzione', models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=models.F('codice_lotto'), tipo='PRODUZIONE'), default=models.Value(None)), output_field=models.CharField(max_length=100))),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotti', to='anagrafiche.articolo')),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotti', to='anagrafiche.fornitore')),
            ],
            options={
                'verbose_name_plural': 'Lotti',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Giacenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaffale', models.CharField(blank=True, default='', max_length=30)),
                ('piano', models.CharField(blank=True, default='', max_length=30)),
                ('quantita', models.DecimalField(decimal_places=6, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ubicazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giacenze', to='anagrafiche.ubicazione')),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giacenze', to='magazzino.lotto')),
            ],
            options={
                'verbose_name_plural': 'Giacenze',
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('CARICO', 'Carico'), ('TRASFERIMENTO', 'Trasferimento'), ('CONSUMO', 'Consumo'), ('PRODUZIONE', 'Produzione'), ('VENDITA', 'Vendita'), ('QUARANTENA', 'Quarantena'), ('REINTEGRO', 'Reintegro'), ('SCARTO', 'Scarto'), ('RETTIFICA', 'Rettifica')], max_length=13)),
                ('quantita', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('scaffale_origine', models.CharField(blank=True, default='', max_length=30)),
                ('piano_origine', models.CharField(blank=True, default='', max_length=30)),
                ('scaffale_destinazione', models.CharField(blank=True, default='', max_length=30)),
                ('piano_destinazione', models.CharField(blank=True, default='', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('eseguito_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_eseguiti', to=settings.AUTH_USER_MODEL)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='magazzino.lotto')),
                ('ubicazione_destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_in_entrata', to='anagrafiche.ubicazione')),
                ('ubicazione_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_in_uscita', to='anagrafiche.ubicazione')),
            ],
            options={
                'verbose_name_plural': 'Movimenti',
                'ordering': ['-data_ora', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RicevimentoLotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ricevimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantita_ricevuta', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('numero_ddt', models.CharField(blank=True, max_length=80)),
                ('data_ddt', models.DateField(blank=True, null=True)),
                ('numero_fattura', models.CharField(blank=True, max_length=80)),
                ('data_fattura', models.DateField(blank=True, null=True)),
                ('numero_colli', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_unita_per_collo', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('quantita_per_unita', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('note', models.TextField(blank=True)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ricevimenti', to='magazzino.lotto')),
            ],
            options={
                'verbose_name_plural': 'Ricevimenti lotto',
                'ordering': ['-data_ricevimento', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.UniqueConstraint(fields=('articolo', 'fornitore', 'codice_lotto'), name='lotto_acquisto_univoco'),
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.UniqueConstraint(fields=('articolo', 'codice_univoco_produzione'), name='lotto_produzione_univoco'),
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fornitore__isnull', False), ('tipo', 'ACQUISTO')), models.Q(('fornitore__isnull', True), ('tipo', 'PRODUZIONE')), _connector='OR'), name='lotto_tipo_fornitore_coerente'),
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.CheckConstraint(condition=models.Q(('codice_lotto', ''), _negated=True), name='lotto_codice_non_vuoto'),
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.CheckConstraint(condition=models.Q(('data_produzione__isnull', True), ('data_scadenza__isnull', True), ('data_scadenza__gte', models.F('data_produzione')), _connector='OR'), name='lotto_date_coerenti'),
        ),
        migrations.AddConstraint(
            model_name='giacenza',
            constraint=models.UniqueConstraint(fields=('lotto', 'ubicazione', 'scaffale', 'piano'), name='giacenza_posizione_univoca'),
        ),
        migrations.AddConstraint(
            model_name='giacenza',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__gte', 0)), name='giacenza_non_negativa'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__gt', 0)), name='movimento_quantita_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('ubicazione_origine__isnull', False), ('ubicazione_destinazione__isnull', False), _connector='OR'), name='movimento_almeno_un_estremo'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ['CARICO', 'PRODUZIONE']), ('ubicazione_destinazione__isnull', False), ('ubicazione_origine__isnull', True)), models.Q(('tipo__in', ['CONSUMO', 'VENDITA', 'SCARTO']), ('ubicazione_destinazione__isnull', True), ('ubicazione_origine__isnull', False)), models.Q(('tipo__in', ['TRASFERIMENTO', 'QUARANTENA', 'REINTEGRO']), ('ubicazione_destinazione__isnull', False), ('ubicazione_origine__isnull', False)), models.Q(('tipo', 'RETTIFICA'), models.Q(models.Q(('ubicazione_destinazione__isnull', False), ('ubicazione_origine__isnull', True)), models.Q(('ubicazione_destinazione__isnull', True), ('ubicazione_origine__isnull', False)), _connector='OR')), _connector='OR'), name='movimento_direzione_coerente'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'RETTIFICA'), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='movimento_rettifica_motivata'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('ubicazione_origine__isnull', False), models.Q(('piano_origine', ''), ('scaffale_origine', '')), _connector='OR'), name='movimento_origine_codici'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('ubicazione_destinazione__isnull', False), models.Q(('piano_destinazione', ''), ('scaffale_destinazione', '')), _connector='OR'), name='movimento_destinazione_codici'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('piano_origine', models.F('piano_destinazione')), ('scaffale_origine', models.F('scaffale_destinazione')), ('ubicazione_origine', models.F('ubicazione_destinazione')), _negated=True), name='movimento_posizioni_distinte'),
        ),
        migrations.AddConstraint(
            model_name='ricevimentolotto',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_ricevuta__gt', 0)), name='ricevimento_quantita_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ricevimentolotto',
            constraint=models.CheckConstraint(condition=models.Q(('numero_colli__isnull', True), ('numero_colli__gt', 0), _connector='OR'), name='ricevimento_colli_positivi'),
        ),
        migrations.AddConstraint(
            model_name='ricevimentolotto',
            constraint=models.CheckConstraint(condition=models.Q(('numero_unita_per_collo__isnull', True), ('numero_unita_per_collo__gt', 0), _connector='OR'), name='ricevimento_unita_positive'),
        ),
        migrations.AddConstraint(
            model_name='ricevimentolotto',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_per_unita__isnull', True), ('quantita_per_unita__gt', 0), _connector='OR'), name='ricevimento_per_unita_positiva'),
        ),
    ]
