# Generated by Django 6.1 on 2026-09-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
        ('magazzino', '0001_initial'),
        ('produzione', '0002_tipolavorazione_cicloproduzione_lavorazione_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lotto',
            name='lavorazione_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotti_generati', to='produzione.lavorazione'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='input_lavorazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='produzione.inputlavorazione'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='output_lavorazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='produzione.outputlavorazione'),
        ),
        migrations.AddConstraint(
            model_name='lotto',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'PRODUZIONE'), ('lavorazione_origine__isnull', True), _connector='OR'), name='lotto_acquisto_senza_lavoro'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('input_lavorazione__isnull', True), ('output_lavorazione__isnull', True), _connector='OR'), name='movimento_input_output_esclusivi'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('input_lavorazione__isnull', True), ('tipo', 'CONSUMO'), _connector='OR'), name='movimento_input_solo_consumo'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('output_lavorazione__isnull', True), ('tipo', 'PRODUZIONE'), _connector='OR'), name='movimento_output_solo_produzione'),
        ),
    ]
