# Generated by Django 6.1 on 2026-09-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_alter_articolo_unita_misura'),
        ('magazzino', '0003_correzionelotto'),
        ('produzione', '0007_lotto_codice_per_articolo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='sessione_semplificata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_output', to='produzione.sessioneproduzionesemplificata'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(('sessione_semplificata__isnull', True), ('tipo', 'PRODUZIONE'), _connector='OR'), name='movimento_sessione_semplice_solo_produzione'),
        ),
    ]
