# Generated by Django 6.1 on 2026-09-12 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_alter_articolo_unita_misura'),
        ('magazzino', '0004_movimento_sessione_semplificata_and_more'),
        ('produzione', '0015_configurazionecontrollosemplificato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movimento',
            name='movimento_direzione_coerente',
        ),
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('CARICO', 'Carico'), ('TRASFERIMENTO', 'Trasferimento'), ('CONSUMO', 'Consumo'), ('PRODUZIONE', 'Produzione'), ('VENDITA', 'Vendita'), ('QUARANTENA', 'Quarantena'), ('REINTEGRO', 'Reintegro'), ('SCARTO', 'Scarto'), ('SCARICO', 'Scarico materiale'), ('RETTIFICA', 'Rettifica')], max_length=13),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ['CARICO', 'PRODUZIONE']), ('ubicazione_destinazione__isnull', False), ('ubicazione_origine__isnull', True)), models.Q(('tipo__in', ['CONSUMO', 'VENDITA', 'SCARTO', 'SCARICO']), ('ubicazione_destinazione__isnull', True), ('ubicazione_origine__isnull', False)), models.Q(('tipo__in', ['TRASFERIMENTO', 'QUARANTENA', 'REINTEGRO']), ('ubicazione_destinazione__isnull', False), ('ubicazione_origine__isnull', False)), models.Q(('tipo', 'RETTIFICA'), models.Q(models.Q(('ubicazione_destinazione__isnull', False), ('ubicazione_origine__isnull', True)), models.Q(('ubicazione_destinazione__isnull', True), ('ubicazione_origine__isnull', False)), _connector='OR')), _connector='OR'), name='movimento_direzione_coerente'),
        ),
        migrations.AddConstraint(
            model_name='movimento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'SCARICO'), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='movimento_scarico_motivato'),
        ),
    ]
