# Generated by Django 6.1 on 2026-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0005_remove_movimento_movimento_direzione_coerente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotto',
            name='stato_prodotto',
            field=models.CharField(choices=[('GENERICO', 'Generico'), ('INVASETTATO', 'Invasettato'), ('PRODOTTO_FINITO', 'Prodotto finito')], default='GENERICO', max_length=20),
        ),
    ]
