# Generated by Django 6.1 on 2026-09-13 16:14

from django.db import migrations, models


def initialize_components(apps, schema_editor):
    lots = apps.get_model("magazzino", "Lotto").objects.using(schema_editor.connection.alias)
    session_model = apps.get_model("produzione", "SessioneProduzioneSemplificata")
    sessions = session_model.objects.using(schema_editor.connection.alias)
    # Durante la migrazione originale il campo si chiamava lotto_prodotto.
    # I test di regressione richiamano anche questa funzione con lo stato più
    # recente dei modelli, nel quale la fonte unica è invece il campo lotto.
    lot_field = "lotto" if any(field.name == "lotto" for field in session_model._meta.fields) else "lotto_prodotto"
    ambiguous = sessions.filter(
        tipo="CONFEZIONAMENTO", stato="CHIUSA", quantita_finale_kg__gt=0,
    ).values(f"lotto_origine__{lot_field}_id")
    lots.filter(models.Q(quantita_confezionata__gt=0) | models.Q(pk__in=ambiguous)).update(confezionamento_verificato=False)
    # Solo per i lotti mai confezionati la componente storica è certa.
    apps.get_model("magazzino", "Movimento").objects.using(schema_editor.connection.alias).filter(
        lotto__stato_prodotto="PRODOTTO_FINITO", lotto__confezionamento_verificato=True
    ).update(componente="SFUSO")


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_alter_articolo_unita_misura'),
        ('magazzino', '0007_lotto_confezionamento'),
        ('produzione', '0019_invasettamento_quantita_pezzi'),
    ]

    operations = [
        migrations.AddField(
            model_name='giacenza',
            name='quantita_confezionata',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='lotto',
            name='confezionamento_verificato',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='componente',
            field=models.CharField(blank=True, choices=[('SFUSO', 'Non confezionato'), ('CONFEZIONATO', 'Confezionato')], default='', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='giacenza',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_confezionata__gte', 0), ('quantita_confezionata__lte', models.F('quantita'))), name='giacenza_confezionata_valida'),
        ),
        migrations.RunPython(initialize_components),
    ]
