# Generated by Django 6.1 on 2026-09-05 10:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('versione', models.CharField(max_length=30)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ricette', to='anagrafiche.articolo')),
            ],
            options={
                'verbose_name_plural': 'Ricette',
                'ordering': ['articolo__codice', 'versione', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RigaRicetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='righe_ricetta', to='anagrafiche.articolo')),
                ('categoria_articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='righe_ricetta', to='anagrafiche.categoriaarticolo')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='produzione.ricetta')),
            ],
            options={
                'verbose_name_plural': 'Righe ricetta',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='ricetta',
            constraint=models.UniqueConstraint(fields=('articolo', 'versione'), name='ricetta_articolo_versione_unica'),
        ),
        migrations.AddConstraint(
            model_name='ricetta',
            constraint=models.CheckConstraint(condition=models.Q(('versione', ''), _negated=True), name='ricetta_versione_non_vuota'),
        ),
        migrations.AddConstraint(
            model_name='rigaricetta',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__gt', 0)), name='riga_ricetta_quantita_positiva'),
        ),
        migrations.AddConstraint(
            model_name='rigaricetta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('articolo__isnull', False), ('categoria_articolo__isnull', True)), models.Q(('articolo__isnull', True), ('categoria_articolo__isnull', False)), _connector='OR'), name='riga_ricetta_un_solo_target'),
        ),
    ]
