# Generated by Django 6.1 on 2026-09-05 15:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
        ('magazzino', '0001_initial'),
        ('produzione', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('genera_lotto', models.BooleanField(default=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi lavorazione',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='CicloProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('stato', models.CharField(choices=[('PIANIFICATO', 'Pianificato'), ('IN_CORSO', 'In corso'), ('COMPLETATO', 'Completato'), ('ANNULLATO', 'Annullato')], default='PIANIFICATO', max_length=11)),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cicli_produzione', to='anagrafiche.articolo')),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cicli_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cicli produzione',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Lavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('PIANIFICATA', 'Pianificata'), ('IN_CORSO', 'In corso'), ('COMPLETATA', 'Completata'), ('ANNULLATA', 'Annullata'), ('INTERROTTA', 'Interrotta')], default='PIANIFICATA', max_length=11)),
                ('data_ora_inizio', models.DateTimeField(blank=True, null=True)),
                ('data_ora_fine', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('ciclo_produzione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lavorazioni', to='produzione.cicloproduzione')),
                ('eseguita_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavorazioni_eseguite', to=settings.AUTH_USER_MODEL)),
                ('ricetta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavorazioni', to='produzione.ricetta')),
                ('tipo_lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lavorazioni', to='produzione.tipolavorazione')),
            ],
            options={
                'verbose_name_plural': 'Lavorazioni',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoInputTipoLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('obbligatorio', models.BooleanField(default=True)),
                ('multiplo', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='anagrafiche.articolo')),
                ('categoria_articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='anagrafiche.categoriaarticolo')),
                ('tipo_lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiti_input', to='produzione.tipolavorazione')),
                ('tipo_lavorazione_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisiti_derivati', to='produzione.tipolavorazione')),
            ],
            options={
                'verbose_name_plural': 'Requisiti input per tipo',
                'ordering': ['ordine', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('note', models.TextField(blank=True)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='magazzino.lotto')),
                ('lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='produzione.lavorazione')),
                ('requisito_input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrazioni', to='produzione.requisitoinputtipolavorazione')),
            ],
            options={
                'verbose_name_plural': 'Input lavorazione',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequisitoOutputTipoLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('obbligatorio', models.BooleanField(default=True)),
                ('multiplo', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('tipo_output', models.CharField(choices=[('PRINCIPALE', 'Principale'), ('SECONDARIO', 'Secondario')], default='PRINCIPALE', max_length=10)),
                ('prefisso_lotto', models.CharField(blank=True, max_length=20)),
                ('articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='anagrafiche.articolo')),
                ('categoria_articolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='anagrafiche.categoriaarticolo')),
                ('tipo_lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiti_output', to='produzione.tipolavorazione')),
            ],
            options={
                'verbose_name_plural': 'Requisiti output per tipo',
                'ordering': ['ordine', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('note', models.TextField(blank=True)),
                ('lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='produzione.lavorazione')),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='magazzino.lotto')),
                ('requisito_output', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrazioni', to='produzione.requisitooutputtipolavorazione')),
            ],
            options={
                'verbose_name_plural': 'Output lavorazione',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='cicloproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('stato__in', ['PIANIFICATO', 'IN_CORSO', 'COMPLETATO', 'ANNULLATO'])), name='ciclo_stato_valido'),
        ),
        migrations.AddConstraint(
            model_name='cicloproduzione',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_chiusura__isnull', True), ('stato__in', ['PIANIFICATO', 'IN_CORSO'])), models.Q(('data_chiusura__isnull', False), ('stato__in', ['COMPLETATO', 'ANNULLATO'])), _connector='OR'), name='ciclo_chiusura_coerente'),
        ),
        migrations.AddConstraint(
            model_name='inputlavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__gt', 0)), name='input_quantita_positiva'),
        ),
        migrations.AddConstraint(
            model_name='outputlavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__gt', 0)), name='output_quantita_positiva'),
        ),
        migrations.AddConstraint(
            model_name='requisitooutputtipolavorazione',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('articolo__isnull', False), ('categoria_articolo__isnull', True)), models.Q(('articolo__isnull', True), ('categoria_articolo__isnull', False)), _connector='OR'), name='req_output_un_solo_target'),
        ),
        migrations.AddConstraint(
            model_name='requisitooutputtipolavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_output__in', ['PRINCIPALE', 'SECONDARIO'])), name='req_output_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='requisitoinputtipolavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('articolo__isnull', True), ('categoria_articolo__isnull', True), _connector='OR'), name='req_input_target_alternativi'),
        ),
        migrations.AddConstraint(
            model_name='requisitoinputtipolavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('articolo__isnull', False), ('categoria_articolo__isnull', False), ('tipo_lavorazione_origine__isnull', False), _connector='OR'), name='req_input_almeno_un_filtro'),
        ),
        migrations.AddConstraint(
            model_name='lavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('stato__in', ['PIANIFICATA', 'IN_CORSO', 'COMPLETATA', 'ANNULLATA', 'INTERROTTA'])), name='lavorazione_stato_valido'),
        ),
        migrations.AddConstraint(
            model_name='lavorazione',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_ora_fine__isnull', True), ('data_ora_inizio__isnull', True), ('eseguita_da__isnull', True), ('stato__in', ['PIANIFICATA', 'ANNULLATA'])), models.Q(('data_ora_fine__isnull', True), ('data_ora_inizio__isnull', False), ('eseguita_da__isnull', False), ('stato', 'IN_CORSO')), models.Q(('data_ora_fine__isnull', False), ('data_ora_inizio__isnull', False), ('eseguita_da__isnull', False), ('stato__in', ['COMPLETATA', 'INTERROTTA'])), _connector='OR'), name='lavorazione_tempi_stato'),
        ),
        migrations.AddConstraint(
            model_name='lavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('data_ora_fine__isnull', True), ('data_ora_fine__gte', models.F('data_ora_inizio')), _connector='OR'), name='lavorazione_fine_dopo_inizio'),
        ),
    ]
