# Generated by Django 6.1 on 2026-09-06 03:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_lotto_lavorazione_origine_and_more'),
        ('produzione', '0002_tipolavorazione_cicloproduzione_lavorazione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisorsaProduttiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('MACCHINA', 'Macchina'), ('TANK', 'Tank'), ('CARRELLO', 'Carrello'), ('ALTRO', 'Altro')], max_length=10)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitaLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(blank=True, max_length=60)),
                ('quantita', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stato', models.CharField(choices=[('ATTIVA', 'Attiva'), ('CHIUSA', 'Chiusa')], default='ATTIVA', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('lavorazione_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unita_generate', to='produzione.lavorazione')),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unita_lavorazione', to='magazzino.lotto')),
                ('risorsa_produttiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unita', to='produzione.risorsaproduttiva')),
            ],
        ),
        migrations.CreateModel(
            name='PartecipazioneUnitaLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni_unita', to='produzione.lavorazione')),
                ('unita_lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipazioni', to='produzione.unitalavorazione')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoFaseUnitaTipoLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obbligatorio', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('tipo_fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='richiesta_per_unita', to='produzione.tipolavorazione')),
                ('tipo_lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasi_unita_richieste', to='produzione.tipolavorazione')),
            ],
            options={
                'ordering': ['ordine', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('tipo_lavorazione', 'tipo_fase'), name='unit_route_unique_phase'), models.UniqueConstraint(fields=('tipo_lavorazione', 'ordine'), name='unit_route_unique_order'), models.CheckConstraint(condition=models.Q(('tipo_lavorazione', models.F('tipo_fase')), _negated=True), name='unit_route_distinct_types')],
            },
        ),
        migrations.CreateModel(
            name='RisorsaLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risorse_utilizzate', to='produzione.lavorazione')),
                ('risorsa_produttiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impieghi', to='produzione.risorsaproduttiva')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lavorazione', 'risorsa_produttiva'), name='work_resource_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='unitalavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__isnull', True), ('quantita__gt', 0), _connector='OR'), name='unit_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='unitalavorazione',
            constraint=models.CheckConstraint(condition=models.Q(('stato__in', ['ATTIVA', 'CHIUSA'])), name='unit_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='partecipazioneunitalavorazione',
            constraint=models.UniqueConstraint(fields=('unita_lavorazione', 'lavorazione'), name='unit_work_unique'),
        ),
    ]
