# Generated by Django 6.1 on 2026-09-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_lotto_lavorazione_origine_and_more'),
        ('produzione', '0003_risorsaproduttiva_unitalavorazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputlavorazione',
            name='riga_ricetta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumi', to='produzione.rigaricetta'),
        ),
        migrations.AlterField(
            model_name='inputlavorazione',
            name='requisito_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrazioni', to='produzione.requisitoinputtipolavorazione'),
        ),
        migrations.AddConstraint(
            model_name='inputlavorazione',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requisito_input__isnull', False), ('riga_ricetta__isnull', True)), models.Q(('requisito_input__isnull', True), ('riga_ricetta__isnull', False)), _connector='OR'), name='input_origine_teorica_unica'),
        ),
    ]
