# Generated by Django 6.1 on 2026-09-07 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
        ('magazzino', '0002_lotto_lavorazione_origine_and_more'),
        ('produzione', '0004_inputlavorazione_riga_ricetta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitooutputtipolavorazione',
            name='schema_lotto',
            field=models.CharField(choices=[('LEGACY', 'Convenzione precedente'), ('RBQB', 'RbQb + data + progressivo'), ('TNK', 'TNK + data + progressivo'), ('FINALE', 'Data + lettera')], default='LEGACY', max_length=10),
        ),
        migrations.AddField(
            model_name='tipolavorazione',
            name='fase_operativa',
            field=models.CharField(blank=True, choices=[('', 'Generica'), ('SEMILAVORATO', 'Semilavorati'), ('ROBOQBO', 'Batch RoboQbo'), ('TANK', 'Formazione tank'), ('INVASETTAMENTO', 'Invasettamento'), ('PASTORIZZAZIONE', 'Seconda pastorizzazione'), ('VUOTO', 'Shock termico e vuoto')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='LineaProduttiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('attiva', models.BooleanField(default=True)),
                ('tipo_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linee_batch', to='produzione.tipolavorazione')),
                ('tipo_invasettamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linee_invasettamento', to='produzione.tipolavorazione')),
                ('tipo_pastorizzazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linee_pastorizzazione', to='produzione.tipolavorazione')),
                ('tipo_tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linee_tank', to='produzione.tipolavorazione')),
                ('tipo_vuoto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linee_vuoto', to='produzione.tipolavorazione')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostazioneLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('BATCH', 'Batch / semilavorati'), ('INVASETTAMENTO', 'Invasettamento')], max_length=20)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postazioni', to='produzione.lineaproduttiva')),
                ('risorsa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='postazione_linea', to='produzione.risorsaproduttiva')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PianoProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_batch', models.PositiveIntegerField()),
                ('creato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='piano_aziendale', to='produzione.cicloproduzione')),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piani_aziendali', to='produzione.ricetta')),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piani', to='produzione.postazionelinea')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionePrelievo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('confermata_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('confermata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisioni', to='produzione.pianoproduzione')),
            ],
        ),
        migrations.CreateModel(
            name='RigaPianoPrelievo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaffale', models.CharField(blank=True, max_length=30)),
                ('piano', models.CharField(blank=True, max_length=30)),
                ('quantita', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magazzino.lotto')),
                ('revisione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='righe', to='produzione.revisioneprelievo')),
                ('riga_ricetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produzione.rigaricetta')),
                ('ubicazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafiche.ubicazione')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PrelievoDaPiano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prelievo_pianificato', to='produzione.inputlavorazione')),
                ('riga_piano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelievi', to='produzione.rigapianoprelievo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessioneInvasettamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aperta_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('articolo_capsule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_capsule', to='anagrafiche.articolo')),
                ('articolo_vasetti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_vasetti', to='anagrafiche.articolo')),
                ('lavorazione', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sessione_invasettamento', to='produzione.lavorazione')),
                ('lotto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sessione_invasettamento', to='magazzino.lotto')),
                ('requisito_capsule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_capsule', to='produzione.requisitoinputtipolavorazione')),
                ('requisito_vasetti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_vasetti', to='produzione.requisitoinputtipolavorazione')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produzione.ricetta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiepilogoInvasettamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasetti_buoni', models.PositiveIntegerField()),
                ('vasetti_scarti', models.PositiveIntegerField()),
                ('capsule_difettose', models.PositiveIntegerField()),
                ('peso_netto_g', models.DecimalField(decimal_places=6, max_digits=18)),
                ('massa_teorica_kg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('massa_reale_kg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('massa_buona_kg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('resa_percentuale', models.DecimalField(decimal_places=6, max_digits=18)),
                ('registrato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('chiuso_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sessione', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='riepilogo', to='produzione.sessioneinvasettamento')),
            ],
        ),
        migrations.CreateModel(
            name='CarrelloSessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('unita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carrello_sessione', to='produzione.unitalavorazione')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrelli', to='produzione.sessioneinvasettamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TankAziendale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa_teorica', models.DecimalField(decimal_places=6, max_digits=18)),
                ('pronto_il', models.DateTimeField(blank=True, null=True)),
                ('lavorazione', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tank_aziendale', to='produzione.lavorazione')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tank', to='produzione.lineaproduttiva')),
                ('lotto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tank_aziendale', to='magazzino.lotto')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produzione.ricetta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrattamentoCarrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('PASTORIZZAZIONE', 'Seconda pastorizzazione'), ('VUOTO', 'Shock termico e vuoto')], max_length=20)),
                ('carrello', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trattamenti', to='produzione.carrellosessione')),
                ('lavorazione', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trattamento_carrello', to='produzione.lavorazione')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fine', models.DateTimeField(blank=True, null=True)),
                ('igienizzazione_confermata_il', models.DateTimeField(blank=True, null=True)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turni_operativi', to=settings.AUTH_USER_MODEL)),
                ('operatore_attivo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turno_attivo_mira', to=settings.AUTH_USER_MODEL)),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turni', to='produzione.postazionelinea')),
                ('postazione_attiva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turno_attivo', to='produzione.postazionelinea')),
            ],
        ),
        migrations.AddField(
            model_name='sessioneinvasettamento',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni', to='produzione.turnooperativo'),
        ),
        migrations.CreateModel(
            name='CodiceProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateField()),
                ('famiglia', models.CharField(choices=[('RBQB', 'RoboQbo'), ('TNK', 'Tank'), ('CRL', 'Carrello'), ('FINALE', 'Lotto finale')], max_length=10)),
                ('numero', models.PositiveIntegerField()),
                ('codice', models.CharField(max_length=100)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anagrafiche.articolo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('articolo', 'giorno', 'famiglia', 'numero'), name='codice_progressivo_unico'), models.UniqueConstraint(fields=('articolo', 'codice'), name='codice_articolo_unico')],
            },
        ),
        migrations.CreateModel(
            name='BatchPiano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('lavorazione', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch_piano', to='produzione.lavorazione')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='produzione.pianoproduzione')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('piano', 'numero'), name='batch_numero_per_piano')],
            },
        ),
        migrations.AddConstraint(
            model_name='pianoproduzione',
            constraint=models.CheckConstraint(condition=models.Q(('numero_batch__gt', 0)), name='piano_batch_positivo'),
        ),
        migrations.AddConstraint(
            model_name='revisioneprelievo',
            constraint=models.UniqueConstraint(fields=('piano', 'numero'), name='revisione_numero_per_piano'),
        ),
        migrations.AddConstraint(
            model_name='rigapianoprelievo',
            constraint=models.CheckConstraint(condition=models.Q(('quantita__gt', 0)), name='riga_piano_quantita_positiva'),
        ),
        migrations.AddConstraint(
            model_name='riepilogoinvasettamento',
            constraint=models.CheckConstraint(condition=models.Q(('massa_reale_kg__gt', 0), ('massa_teorica_kg__gt', 0), ('peso_netto_g__gt', 0)), name='riepilogo_pesi_positivi'),
        ),
        migrations.AddConstraint(
            model_name='trattamentocarrello',
            constraint=models.UniqueConstraint(fields=('carrello', 'fase'), name='trattamento_fase_carrello'),
        ),
        migrations.AddConstraint(
            model_name='turnooperativo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fine__isnull', True), ('operatore_attivo__isnull', False), ('postazione_attiva__isnull', False)), models.Q(('fine__isnull', False), ('operatore_attivo__isnull', True), ('postazione_attiva__isnull', True)), _connector='OR'), name='turno_attivita_coerente'),
        ),
    ]
