# Generated by Django 6.1 on 2026-09-09 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0002_lotto_lavorazione_origine_and_more'),
        ('produzione', '0005_requisitooutputtipolavorazione_schema_lotto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlloSessioneSemplificata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BATCH', 'Batch'), ('TANK', 'Tank'), ('CARRELLO', 'Carrello')], max_length=10)),
                ('numero', models.PositiveIntegerField()),
                ('inizio', models.DateTimeField(blank=True, null=True)),
                ('fine', models.DateTimeField(blank=True, null=True)),
                ('esito_tracciato_termico', models.CharField(blank=True, choices=[('C', 'Conforme'), ('NC', 'Non conforme'), ('NA', 'Non applicabile')], max_length=2)),
                ('gradi_brix', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('esito_pastorizzazione', models.CharField(blank=True, choices=[('C', 'Conforme'), ('NC', 'Non conforme'), ('NA', 'Non applicabile')], max_length=2)),
                ('esito_shock_vuoto', models.CharField(blank=True, choices=[('C', 'Conforme'), ('NC', 'Non conforme'), ('NA', 'Non applicabile')], max_length=2)),
                ('registrato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('registrato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='SessioneProduzioneSemplificata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ROBOQBO', 'RoboQbo'), ('INVASETTAMENTO', 'Invasettamento')], max_length=20)),
                ('lotto_codice', models.CharField(max_length=100)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=10)),
                ('numero_batch_previsti', models.PositiveIntegerField(blank=True, null=True)),
                ('igienizzazione_confermata_il', models.DateTimeField(blank=True, null=True)),
                ('aperta_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('aperta_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_semplificate_aperte', to=settings.AUTH_USER_MODEL)),
                ('chiusa_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_semplificate_chiuse', to=settings.AUTH_USER_MODEL)),
                ('lotto_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_invasettamento', to='produzione.sessioneproduzionesemplificata')),
                ('postazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_semplificate', to='produzione.postazionelinea')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_semplificate', to='produzione.ricetta')),
            ],
            options={
                'ordering': ['-aperta_il', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RiepilogoSessioneSemplificata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasetti_buoni', models.PositiveIntegerField(default=0)),
                ('vasetti_scartati', models.PositiveIntegerField(default=0)),
                ('vasetti_quarantena', models.PositiveIntegerField(default=0)),
                ('capsule_difettose', models.PositiveIntegerField(default=0)),
                ('peso_netto_g', models.DecimalField(decimal_places=6, max_digits=18)),
                ('registrato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sessione', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='riepilogo_finale', to='produzione.sessioneproduzionesemplificata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrelievoSessioneSemplificata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_kg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('numero_batch', models.PositiveIntegerField(blank=True, null=True)),
                ('registrato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('lotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelievi_sessioni_semplificate', to='magazzino.lotto')),
                ('movimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prelievo_sessione_semplificata', to='magazzino.movimento')),
                ('registrato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelievi', to='produzione.sessioneproduzionesemplificata')),
            ],
            options={
                'ordering': ['registrato_il', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='NonConformitaSessioneSemplificata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('quantita_coinvolta_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('vasetti_coinvolti', models.PositiveIntegerField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=10)),
                ('aperta_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('aperta_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nc_semplificate_aperte', to=settings.AUTH_USER_MODEL)),
                ('chiusa_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_semplificate_chiuse', to=settings.AUTH_USER_MODEL)),
                ('controllo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita', to='produzione.controllosessionesemplificata')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_conformita_semplificate', to='produzione.sessioneproduzionesemplificata')),
            ],
            options={
                'ordering': ['-aperta_il', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='controllosessionesemplificata',
            name='sessione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlli', to='produzione.sessioneproduzionesemplificata'),
        ),
        migrations.AddConstraint(
            model_name='sessioneproduzionesemplificata',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chiusa_da__isnull', True), ('chiusa_il__isnull', True), ('stato', 'APERTA')), models.Q(('chiusa_da__isnull', False), ('chiusa_il__isnull', False), ('stato', 'CHIUSA')), _connector='OR'), name='sessione_semplice_chiusura_coerente'),
        ),
        migrations.AddConstraint(
            model_name='prelievosessionesemplificata',
            constraint=models.CheckConstraint(condition=models.Q(('quantita_kg__gt', 0)), name='prelievo_semplice_quantita_positiva'),
        ),
        migrations.AddConstraint(
            model_name='controllosessionesemplificata',
            constraint=models.UniqueConstraint(fields=('sessione', 'tipo', 'numero'), name='controllo_semplice_numero_unico'),
        ),
    ]
