# Generated by Django 6.1 on 2026-09-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0004_movimento_sessione_semplificata_and_more'),
        ('produzione', '0007_lotto_codice_per_articolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioneproduzionesemplificata',
            name='lotto_prodotto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessione_semplificata_origine', to='magazzino.lotto'),
        ),
        migrations.AddField(
            model_name='sessioneproduzionesemplificata',
            name='numero_lavorazioni_previste',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioneproduzionesemplificata',
            name='quantita_finale_kg',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sessioneproduzionesemplificata',
            name='quantita_prevista_kg',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sessioneproduzionesemplificata',
            name='tipo',
            field=models.CharField(choices=[('SEMILAVORATO', 'Semilavorato'), ('ROBOQBO', 'RoboQbo'), ('INVASETTAMENTO', 'Invasettamento')], max_length=20),
        ),
    ]
