# Generated by Django 6.1 on 2026-09-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0008_sessioneproduzionesemplificata_lotto_prodotto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioneproduzionesemplificata',
            name='postazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessioni_semplificate', to='produzione.postazionelinea'),
        ),
    ]
