# Generated by Django 6.1 on 2026-09-09 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0004_movimento_sessione_semplificata_and_more'),
        ('produzione', '0009_alter_sessioneproduzionesemplificata_postazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessioneproduzionesemplificata',
            name='sessione_semplice_chiusura_coerente',
        ),
        migrations.AddField(
            model_name='sessioneproduzionesemplificata',
            name='iniziata_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessioneproduzionesemplificata',
            name='stato',
            field=models.CharField(choices=[('PIANIFICATA', 'Pianificata'), ('APERTA', 'Aperta'), ('CHIUSA', 'Chiusa'), ('ANNULLATA', 'Annullata')], default='PIANIFICATA', max_length=11),
        ),
        migrations.AddConstraint(
            model_name='sessioneproduzionesemplificata',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chiusa_da__isnull', True), ('chiusa_il__isnull', True), ('stato__in', ['PIANIFICATA', 'APERTA'])), models.Q(('chiusa_da__isnull', False), ('chiusa_il__isnull', False), ('stato__in', ['CHIUSA', 'ANNULLATA'])), _connector='OR'), name='sessione_semplice_chiusura_coerente'),
        ),
    ]
