# Generated by Django 6.1 on 2026-09-10 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0012_controllo_semplice_campi_per_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformitasessionesemplificata',
            name='presa_in_carico_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nc_semplificate_gestite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconformitasessionesemplificata',
            name='presa_in_carico_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformitasessionesemplificata',
            name='stato',
            field=models.CharField(choices=[('APERTA', 'Aperta'), ('IN_GESTIONE', 'In gestione'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=12),
        ),
        migrations.CreateModel(
            name='AzioneNCSessioneSemplificata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('registrata_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('non_conformita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='azioni', to='produzione.nonconformitasessionesemplificata')),
                ('registrata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='azioni_nc_semplificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registrata_il', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='VerificaNCSessioneSemplificata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esito', models.CharField(choices=[('EFFICACE', 'Efficace'), ('NON_EFFICACE', 'Non efficace')], max_length=12)),
                ('descrizione', models.TextField()),
                ('verificata_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('non_conformita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifiche', to='produzione.nonconformitasessionesemplificata')),
                ('verificata_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifiche_nc_semplificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['verificata_il', 'pk'],
            },
        ),
    ]
