# Generated by Django 6.1 on 2026-09-10 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0013_nonconformitasessionesemplificata_presa_in_carico_da_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociazioneTankBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='associazione_tank', to='produzione.controllosessionesemplificata')),
                ('registrato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associazioni_tank_batch_registrate', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associazioni_batch', to='produzione.controllosessionesemplificata')),
            ],
            options={
                'ordering': ['tank__numero', 'batch__numero', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('tank', models.F('batch')), _negated=True), name='tank_batch_distinti')],
            },
        ),
    ]
