# Generated by Django 6.1 on 2026-09-11 12:41

from django.conf import settings
from django.db import migrations, models


def configura_controlli_iniziali(apps, schema_editor):
    Configurazione = apps.get_model('produzione', 'ConfigurazioneControlloSemplificato')
    righe = [
        ('SEMILAVORATO', 'PASTORIZZAZIONE', 'Pastorizzazione', 10),
        ('SEMILAVORATO', 'SHOCK_VUOTO', 'Shock termico e vuoto', 20),
        ('ROBOQBO_BATCH', 'INIZIO', 'Ora di inizio', 10),
        ('ROBOQBO_BATCH', 'FINE', 'Ora di fine', 20),
        ('ROBOQBO_BATCH', 'TRACCIATO', 'Tracciato 82 °C × 60 s', 30),
        ('ROBOQBO_TANK', 'BRIX', '°Brix', 10),
        ('ROBOQBO_TANK', 'PH', 'pH', 20),
        ('INVASETTAMENTO_CARRELLO', 'PASTORIZZAZIONE', '2ª pastorizzazione', 10),
        ('INVASETTAMENTO_CARRELLO', 'SHOCK_VUOTO', 'Shock termico e vuoto', 20),
    ]
    for ambito, codice, nome, ordine in righe:
        Configurazione.objects.update_or_create(
            ambito=ambito, codice=codice,
            defaults={'nome': nome, 'ordine': ordine, 'obbligatorio': True, 'attivo': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('produzione', '0014_associazionetankbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneControlloSemplificato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('SEMILAVORATO', 'Semilavorati'), ('ROBOQBO_BATCH', 'RoboQbo · Batch'), ('ROBOQBO_TANK', 'RoboQbo · Tank'), ('INVASETTAMENTO_CARRELLO', 'Invasettamento · Carrello')], max_length=30)),
                ('codice', models.CharField(choices=[('INIZIO', 'Ora di inizio'), ('FINE', 'Ora di fine'), ('TRACCIATO', 'Tracciato 82 °C × 60 s'), ('BRIX', '°Brix'), ('PH', 'pH'), ('PASTORIZZAZIONE', 'Pastorizzazione'), ('SHOCK_VUOTO', 'Shock termico e vuoto')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.PositiveSmallIntegerField(default=10)),
                ('obbligatorio', models.BooleanField(default=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ambito', 'ordine', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='controllosessionesemplificata',
            name='controllo_semplice_campi_per_tipo',
        ),
        migrations.AlterField(
            model_name='controllosessionesemplificata',
            name='tipo',
            field=models.CharField(choices=[('SEMILAVORATO', 'Semilavorato'), ('BATCH', 'Batch'), ('TANK', 'Tank'), ('CARRELLO', 'Carrello')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='controllosessionesemplificata',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('esito_pastorizzazione', ''), ('esito_shock_vuoto', ''), ('gradi_brix__isnull', True), ('ph__isnull', True), ('tipo', 'BATCH')), models.Q(('esito_tracciato_termico', ''), ('fine__isnull', True), ('gradi_brix__isnull', True), ('inizio__isnull', True), ('ph__isnull', True), ('tipo', 'SEMILAVORATO')), models.Q(('esito_pastorizzazione', ''), ('esito_shock_vuoto', ''), ('esito_tracciato_termico', ''), ('fine__isnull', True), ('inizio__isnull', True), ('tipo', 'TANK')), models.Q(('esito_tracciato_termico', ''), ('fine__isnull', True), ('gradi_brix__isnull', True), ('inizio__isnull', True), ('ph__isnull', True), ('tipo', 'CARRELLO')), _connector='OR'), name='controllo_semplice_campi_per_tipo'),
        ),
        migrations.AddConstraint(
            model_name='configurazionecontrollosemplificato',
            constraint=models.UniqueConstraint(fields=('ambito', 'codice'), name='config_controllo_semplice_unica'),
        ),
        migrations.RunPython(configura_controlli_iniziali, migrations.RunPython.noop),
    ]
