# Generated by Django 6.1 on 2026-09-12 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0005_remove_movimento_movimento_direzione_coerente_and_more'),
        ('produzione', '0015_configurazionecontrollosemplificato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='azionencsessionesemplificata',
            name='movimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='azione_nc_sessione_semplificata', to='magazzino.movimento'),
        ),
        migrations.AddField(
            model_name='azionencsessionesemplificata',
            name='tipo',
            field=models.CharField(choices=[('AZIONE', 'Azione documentale'), ('SCARTO', 'Scarto dal magazzino')], default='AZIONE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='azionencsessionesemplificata',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movimento__isnull', False), ('tipo', 'SCARTO')), models.Q(('movimento__isnull', True), ('tipo', 'AZIONE')), _connector='OR'), name='azione_nc_semplice_movimento_coerente'),
        ),
    ]
