# Generated by Django 6.1 on 2026-09-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0008_giacenza_quantita_confezionata_and_more'),
        ('produzione', '0019_invasettamento_quantita_pezzi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioneproduzionesemplificata',
            name='confezionamento_giacenza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confezionamenti', to='magazzino.giacenza'),
        ),
    ]
